### ISSUE TITLE
importを試す

### ISSUE THREAD

**Issue by kekoyana** [kekoyana/rails6_demo#9]
bulkinsertを試す

**Comment by kekoyana** [comment]
## 試してみた
```rb
[27] pry(main)> data = %w(foo bar).map { |name| { name: name, created_at: Time.current, updated_at: Time.current } }
=> [{:name=>"foo", :created_at=>Fri, 22 Mar 2019 13:37:35 UTC +00:00, :updated_at=>Fri, 22 Mar 2019 13:37:35 UTC +00:00},
 {:name=>"bar", :created_at=>Fri, 22 Mar 2019 13:37:35 UTC +00:00, :updated_at=>Fri, 22 Mar 2019 13:37:35 UTC +00:00}]
[28] pry(main)> User.insert_all!(data)
  Bulk Insert (7.5ms)  INSERT INTO "users"("name","created_at","updated_at") VALUES ('foo', '2019-03-22 13:37:35.748059', '2019-03-22 13:37:35.748087'), ('bar', '2019-03-22 13:37:35.748110', '2019-03-22 13:37:35.748134') RETURNING "id"
=> #<ActiveRecord::Result:0x0000561a5cc31c80
 @column_types=
  {"id"=>#<ActiveModel::Type::Integer:0x0000561a5b372230 @limit=8, @precision=nil, @range=-9223372036854775808...9223372036854775808, @scale=nil>},
 @columns=["id"],
 @hash_rows=nil,
 @rows=[[5], [6]]>
[29] pry(main)> User.all
  User Load (0.8ms)  SELECT "users".* FROM "users"
=> [#<User:0x0000561a5ccad1c8 id: 5, name: "foo", role: nil, created_at: Fri, 22 Mar 2019 13:37:35 UTC +00:00, updated_at: Fri, 22 Mar 2019 13:37:35 UTC +00:00>,
 #<User:0x0000561a5ccad0d8 id: 6, name: "bar", role: nil, created_at: Fri, 22 Mar 2019 13:37:35 UTC +00:00, updated_at: Fri, 22 Mar 2019 13:37:35 UTC +00:00>]
```

**Comment by kekoyana** [comment]
# NG集
## created_at, updated_atは埋めないとダメ
```rb
[34] pry(main)> data = %w(foo bar).map { |name| { name: name } }
=> [{:name=>"foo"}, {:name=>"bar"}]
[35] pry(main)> User.insert_all!(data)
  Bulk Insert (1.7ms)  INSERT INTO "users"("name") VALUES ('foo'), ('bar') RETURNING "id"
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (7, foo, null, null, null).
from /work/vendor/bundle/bundler/gems/rails-f40860800c23/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `async_exec_params'
Caused by PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (7, foo, null, null, null).

from /work/vendor/bundle/bundler/gems/rails-f40860800c23/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `async_exec_params'
```

## オブジェクトもダメだった
```
[40] pry(main)> user1 = User.new(name: "sono1")
=> #<User:0x0000561a5b0d84c0 id: nil, name: "sono1", role: nil, created_at: nil, updated_at: nil>
[41] pry(main)> user2 = User.new(name: "sono2")
=> #<User:0x0000561a5b192b40 id: nil, name: "sono2", role: nil, created_at: nil, updated_at: nil>
[42] pry(main)> users = %w(foo bar).map { |name| User.new(name: name, created_at: Time.current, updated_at: Time.current) }
=> [#<User:0x0000561a5b2bcf20
  id: nil,
  name: "foo",
  role: nil,
  created_at: Fri, 22 Mar 2019 13:47:29 UTC +00:00,
  updated_at: Fri, 22 Mar 2019 13:47:29 UTC +00:00>,
 #<User:0x0000561a5b2bc840
  id: nil,
  name: "bar",
  role: nil,
  created_at: Fri, 22 Mar 2019 13:47:29 UTC +00:00,
  updated_at: Fri, 22 Mar 2019 13:47:29 UTC +00:00>]
[43] pry(main)> User.insert_all!(users)
NoMethodError: undefined method `keys' for #<User:0x0000561a5b2bcf20>
from /work/vendor/bundle/bundler/gems/rails-f40860800c23/activemodel/lib/active_model/attribute_methods.rb:430:in `method_missing'
```

**Comment by kekoyana** [comment]
オブジェクトでやるならこんな感じかな
```rb
[61] pry(main)> users = %w(foo bar).map { |name| User.new(name: name, created_at: Time.current, updated_at: Time.current) }
=> [#<User:0x0000561a5c5d6cf0
  id: nil,
  name: "foo",
  role: nil,
  created_at: Fri, 22 Mar 2019 13:52:38 UTC +00:00,
  updated_at: Fri, 22 Mar 2019 13:52:38 UTC +00:00>,
 #<User:0x0000561a5c5d6728
  id: nil,
  name: "bar",
  role: nil,
  created_at: Fri, 22 Mar 2019 13:52:38 UTC +00:00,
  updated_at: Fri, 22 Mar 2019 13:52:38 UTC +00:00>]
[62] pry(main)> User.insert_all!(users.map { |user| user.attributes.slice(*%w(name created_at updated_at)) })
  Bulk Insert (8.2ms)  INSERT INTO "users"("name","created_at","updated_at") VALUES ('foo', '2019-03-22 13:52:38.211656', '2019-03-22 13:52:38.211689'), ('bar', '2019-03-22 13:52:38.211854', '2019-03-22 13:52:38.211871') RETURNING "id"
=> #<ActiveRecord::Result:0x0000561a5c6f7a58
 @column_types=
  {"id"=>#<ActiveModel::Type::Integer:0x0000561a5b372230 @limit=8, @precision=nil, @range=-9223372036854775808...9223372036854775808, @scale=nil>},
 @columns=["id"],
 @hash_rows=nil,
 @rows=[[10], [11]]>
```

**Comment by kekoyana** [comment]
満足した
